Tracking tags
Runnable/loki pull request #33
Opened 2016-09-26 21:37 UTC by podviaznikov

2016-09-26 22:15 UTC, anandkumarpatel commented on lib/base.js
> +      datadogTags: opts.datadogTags || {}
+1 but you dont have a test for datadogTags ?

2016-09-26 22:16 UTC, anandkumarpatel requested changes

2016-09-26 22:16 UTC, podviaznikov commented on lib/base.js
> +      datadogTags: opts.datadogTags || {}
will add it. Good point

2016-09-27 22:45 UTC, podviaznikov commented on lib/base.js
> +      datadogTags: opts.datadogTags || {}
done

2016-09-28 02:59 UTC, anandkumarpatel commented
Approved

2016-09-28 16:11 UTC, anandkumarpatel approved these changes

2016-09-28 18:50 UTC, merged